### ISSUE TITLE
Add RxJava support

### ISSUE THREAD

**Issue by Wavesonics** [Jearil/SimpleNoSQL#15]
Since the data retrieval is already async by default, it'd be pretty sweet to provide a option to return an RxJava Observable from which to receive the data.

Retrofit does this in an optional way so you don't have to have RxJava in your project, but if you do it all just works. Not exactly sure how they accomplish that.

RxJava:
https://github.com/ReactiveX/RxJava

Android version of RxJava:
https://github.com/ReactiveX/RxAndroid

Retrofit:
https://github.com/square/retrofit

**Comment by Jearil** [comment]
I'm fine with someone building an RxJava wrapper around SimpleNoSQL, but I don't want to include any references to it in the project (Retrofit does include RxJava)
