### ISSUE TITLE
New entity with the same id overrides existing entity.

### ISSUE THREAD

**Issue by mtwain** [Jearil/SimpleNoSQL#17]
Need check like "isEntityWithSameIdExists(String id)"

**Comment by Jearil** [comment]
hmm. So we can do something like that but it'll be an async call with a callback. We could also do something where you store an entity and have the listener return any replaced values maybe? You can also always do a get before you do a put using the current system.

**Comment by Jearil** [comment]
This is hard to tell if it's a bug or a feature. This library is meant to be easy to use and streamlined. If you store something with an ID, it's stored with that ID regardless of if there was something already there. Checking if the ID already exists requires an additional round trip to the database, which I'd rather not incur with each query.
