### ISSUE TITLE
How  to Support List  like HashMap?

### ISSUE THREAD

**Issue by longtaoge** [Jearil/SimpleNoSQL#28]
I want save a list in entify  like HashMap 

public void testSaveEntities2() throws Throwable {

		NoSQLEntity<SampleBean2> entity = new NoSQLEntity<SampleBean2>(
				"bucket", "entityId");
		SampleBean2 data = new SampleBean2();
		data.setField1("abc");
		data.setId(9);
		List<User> mUsers = new ArrayList<User>();
		for (int i = 0; i < 100; i++) {

			User mUser = new User();
			mUser.setAge("15" + i);
			mUser.setName("name" + i);
			mUsers.add(mUser);

		}
		
		data.setmUsers(mUsers);
		entity.setData(data);
		//NoSQL.with(context).using(SampleBean2.class).bucketId("bucket")
	   // .entityId("entityId").delete();
		NoSQL.with( getInstrumentation().getTargetContext()).using(SampleBean2.class).save(entity);

	}

but  the result like this 

![image](https://github.com/longtaoge/SimpleNoSQLDome/blob/master/res/drawable/nosql.png)

[link](https://github.com/longtaoge/SimpleNoSQLDome/blob/master/src/com/colintmiller/simplenosql/test2/NoSQLSaveTaskTest.java)

How  to Support List  like HashMap?

**Comment by Jearil** [comment]
Unfortunately your image doesn't work so I'm not sure what your error is. By default, your data is Serialized using [Gson](https://github.com/google/gson/blob/master/UserGuide.md). You will need to make sure your objects are serializable via that library. Alternatively you may create your own Serializer and Deserializer by implementing [DataSerializer](https://github.com/Jearil/SimpleNoSQL/blob/master/SimpleNoSQL/src/main/java/com/colintmiller/simplenosql/DataSerializer.java) and [DataDeserializer](https://github.com/Jearil/SimpleNoSQL/blob/master/SimpleNoSQL/src/main/java/com/colintmiller/simplenosql/DataSerializer.java).

    NoSQL.with(context)
      .withSerializer(serializer)
      .withDeserializer(deserializer)
      .using(SampleBean2.class)
      .save(entity);

**Comment by longtaoge** [comment]
the Serialized is ok and i am use the Gson also ,  my mean  is  if a entity contains a long list ,like SampleBean2  ' entity  ，the entity will save as a long json String in db ,eg : if the list 's size is big than 1000, sqlite will save the String failure.

**Comment by Jearil** [comment]
Ok. I'll work on changing the DB to store a byte array which would be
better.

**Comment by longtaoge** [comment]
that may be good  idea , i tested the  hawk  can saved more data on Once I/O

**Comment by Jearil** [comment]
Saving as a byte[] is now in the github. You can build your own copy of the library and try that until I publish a new build to sonatype.
